homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago

  customize: !include customize.yaml

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:


# Weather Prediction
sensor:
  platform: yr


# Text to speech
tts:
  platform: google


# Lights
light:
  platform: hue
  host: 192.168.88.32

# enable wemo component
wemo:
  static:
    - 192.168.88.20


media_player:
  # enable roku component
- platform: roku
  host: 192.168.88.30
  # enable plex component
- platform: plex
  # enable bedroom google cast
- platform: cast
  host: 192.168.88.33
  # enable google home cast
- platform: cast
  host: 192.168.88.31

# connect to mqtt broker
mqtt:
  broker: !secret mqtt_ip
  port: !secret mqtt_port
  client_id: homeassistant
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 1
    retain: true
  will_message:
    topic: 'hass/status'
    payload: 'offline'
    qos: 1
    retain: true

# my computer
#device_tracker:
#  - platform: ping
#    hosts:
#      router: 192.168.88.250

# Add owntracks for presence detection
device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
    track_new_devices: no

# enable zwave
zwave:
  usb_path: /dev/ttyACM0
  config_path: /home/homeassistant/python-openzwave/openzwave/config

# Add an input select which controls the white balance of lights in one of three modes
input_select:
  light_mode:
    name: Light mode
    options:
      - Morning
      - Daytime
      - Evening
      - Bedtime
    initial: Daytime
    icon: mdi:white-balance-sunny


zone:
  name: Home
  # Set geographical location of the zone, along with raidus.
  # Conveniently re-uses the home location from the configuration of homeassistant
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: !secret home_zone_radius
  # Set icon to material design icon, home
  icon: mdi:home

zone 2:
  name: Work
  latitude: !secret work_latitude
  longitude: !secret work_longitude
  radius: !secret work_zone_radius
  # Set icon to material design icon, briefcase
  icon: mdi:briefcase

# group "white" lights
group:
  white_lights:
    #friendly_name: Lights
    entities:
      - light.kitchen
      - light.hue_color_lamp_3
      - light.hue_color_lamp_4

# control "white" lights
script:
  candlelight:
    alias: "Good night"
    sequence:
      - service: light.turn_on
        entity_id: group.white_lights
        data:
          color_temp: 500
          brightness: 120
  sunlight:
    alias: "Good morning"
    sequence:
      - service: light.turn_on
        entity_id: group.white_lights
        data:
          color_temp: 160
          brightness: 255

# Test configuration: add an empty webpage to the sidebar
#panel_custom:
#  - name: testpanel
#    sidebar_title: testpanel
#    sidebar_icon: mdi:work
#    url_path: testpanel
#    webcomponent_path: /home/hass/.homeassistant/www/hello.html

# Add some local webpages to the home assistant front end
panel_iframe:
# Add the router webpage to the frontend
  router:
    title: 'Router'
    url: !secret router_webpage
    icon: mdi:access-point-network
# Add the pihole webpage to the frontend
  pihole:
    title: 'DNS'
    url: !secret pihole_webpage
    icon: mdi:close-network

# rule for turning off and on the bathroom nightlight based on motion detection
automation:
  alias: Turn on bathroom nightlight when motion is detected
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_pir_motion_sensor_sensor_3_0
    from: 'off'
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: light.hue_lightstrip_2

automation 2:
  alias: Turn off bathroom nightlight when motion is not detected
  initial_state: true
  hide_entity: true
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_pir_motion_sensor_sensor_3_0
    from: 'on'
    to: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: light.hue_lightstrip_2
