homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago

  customize: !include customize.yaml

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:


# Weather Prediction
sensor:
  - platform: yr
  - platform: darksky
    name: weather
    api_key: !secret darksky_api
    monitored_conditions:
      - temperature
      - humidity
      - precip_probability
      - precip_intensity
      - wind_speed
      - pressure
      - wind_bearing
      - apparent_temperature
      - icon


# Text to speech
tts:
  platform: google


# Lights
light:
  platform: hue
  host: 192.168.88.32
  allow_hue_groups: false

# enable wemo component
wemo:
  static:
    - 192.168.88.20
    - 192.168.88.21


media_player:
    # enable roku component
  - platform: roku
    host: 192.168.88.30
    # enable plex component
  - platform: plex
    # enable bedroom google cast
  - platform: cast
    host: 192.168.88.33
    # enable google home cast
  - platform: cast
    host: 192.168.88.31

# connect to mqtt broker
mqtt:
  broker: !secret mqtt_ip
  port: !secret mqtt_port
  client_id: homeassistant
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 1
    retain: true
  will_message:
    topic: 'hass/status'
    payload: 'offline'
    qos: 1
    retain: true

# add flux for changing lighting colors based on time
switch:
  platform: flux
  lights:
    - light.hue_color_lamp_1
    - light.hue_color_lamp_2
    - light.hue_color_lamp_3
    - light.hue_color_lamp_4
  name: flux
  start_time: '6:30'
  stop_time: '23:00'
  start_colortemp: 4000
  sunset_colortemp: 3000
  stop_colortemp: 1900
  #brightness: 255

# my computer
#device_tracker:
#  - platform: ping
#    hosts:
#      router: 192.168.88.250

# Add owntracks for presence detection
device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
    track_new_devices: no
#  - platform: nmap_tracker
#    hosts: 192.168.88.150

# enable zwave
zwave:
  usb_path: /dev/ttyACM0
  config_path: /home/homeassistant/python-openzwave/openzwave/config

# Add an input select which controls the white balance of lights in one of three modes
input_select:
  light_mode:
    name: Light mode
    options:
      - Morning
      - Daytime
      - Evening
      - Bedtime
    initial: Daytime
    icon: mdi:white-balance-sunny


zone:
  name: Home
  # Set geographical location of the zone, along with raidus.
  # Conveniently re-uses the home location from the configuration of homeassistant
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  radius: !secret home_zone_radius
  # Set icon to material design icon, home
  icon: mdi:home

zone 2:
  name: Work
  latitude: !secret work_latitude
  longitude: !secret work_longitude
  radius: !secret work_zone_radius
  # Set icon to material design icon, briefcase
  icon: mdi:briefcase

# group "white" lights
group:
  default_view:
    view: yes
    entities:
      - group.white_lights
      - media_player.roku4
      - media_player.bedroom_speakers
      - media_player.living_room_home
      - switch.wemo_bedroom_switch
      - switch.flux
  white_lights:
    name: Lights
    entities:
      - group.warehouse_lights
      - light.hue_color_lamp_3
      - light.hue_color_lamp_4
  warehouse_lights:
    name: Warehouse Lights
    view: no
    icon: mdi:lightbulb
    entities:
      - light.hue_color_lamp_1
      - light.hue_color_lamp_2

# control "white" lights
script:
  # bedtime
  bedtime_light:
    sequence:
      - service: light.turn_on
        entity_id: group.white_lights
        data:
          color_temp: 500
          brightness: 120
  # morning
  morning_light:
    sequence:
      - service: light.turn_on
        entity_id: group.white_lights
        data:
          color_temp: 160
          brightness: 255
  # daytime
  daytime_light:
    sequence:
      - service: light.turn_on
        entity_id: group.white_lights
        data:
          color_temp: 280
          brightness: 255
  # evening
  evening_light:
    sequence:
      - service: light.turn_on
        entity_id: group.white_lights
        data:
          color_temp: 350
          brightness: 200


# Test configuration: add an empty webpage to the sidebar
#panel_custom:
#  - name: testpanel
#    sidebar_title: testpanel
#    sidebar_icon: mdi:work
#    url_path: testpanel
#    webcomponent_path: /home/hass/.homeassistant/www/hello.html

# Add some local webpages to the home assistant front end
panel_iframe:
# Add the router webpage to the frontend
  router:
    title: 'Router'
    url: !secret router_webpage
    icon: mdi:access-point-network
# Add the pihole webpage to the frontend
  pihole:
    title: 'DNS'
    url: !secret pihole_webpage
    icon: mdi:close-network

automation:
  # rules for turning off and on the bathroom nightlight based on motion detection
  - alias: Turn on bathroom nightlight when motion is detected
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id: binary_sensor.ecolink_pir_motion_sensor_sensor_3_0
      from: 'off'
      to: 'on'
    action:
      service: homeassistant.turn_on
      entity_id: light.hue_lightstrip_2

  - alias: Turn off bathroom nightlight when motion is not detected
    initial_state: true
    hide_entity: true
    trigger:
      platform: state
      entity_id: binary_sensor.ecolink_pir_motion_sensor_sensor_3_0
      from: 'on'
      to: 'off'
    action:
      service: homeassistant.turn_off
      entity_id: light.hue_lightstrip_2

  # rules for turning on the lightstrip when computer is running
  - alias: Turn on the desk lightstrip when outlet draws 25W or more
    initial_state: true
    hide_entity: true
    trigger:
      platform: template
      value_template: '{% if states.switch.computer_outlet.state %}{{ states.switch.computer_outlet.attributes.current_power_mwh > 25000 }}{% endif %}'
    action:
      service: homeassistant.turn_on
      entity_id: light.hue_lightstrip_1

  - alias: Turn off the desk lightstrip when outlet draws 25W or less
    initial_state: true
    hide_entity: true
    trigger:
      platform: template
      value_template: '{% if states.switch.computer_outlet.state %}{{ states.switch.computer_outlet.attributes.current_power_mwh < 25000 }}{% endif %}'
    action:
      service: homeassistant.turn_off
      entity_id: light.hue_lightstrip_1

  # rule for coming home
  - alias: Lights on when home
    initial_state: true
    hide_entity: true
    trigger:
      platform: zone
      entity_id: device_tracker.iansmcf_myphone
      zone: zone.home
      event: enter
    action:
      - service: homeassistant.turn_on
        entity_id: group.white_lights

  # rule for leaving home
  - alias: Lights off when not home
    initial_state: true
    hide_entity: true
    trigger:
      platform: zone
      entity_id: device_tracker.iansmcf_myphone
      zone: zone.home
      event: leave
    action:
      - service: homeassistant.turn_off
        entity_id: group.white_lights
      - service: homeassistant.turn_off
        entity_id: switch.wemo_bedroom_switch
